/* libtiff/tiffconf.h.  Generated by configure.  */
/*
  Configuration defines for installed libtiff.
  This file maintained for backward compatibility. Do not use definitions
  from this file in your programs.
*/

#ifndef _TIFFCONF_
#define _TIFFCONF_

#include "tif_config.h"
//
///* Define to 1 if the system has the type `int16'. */
///* #undef HAVE_INT16 */
//
///* Define to 1 if the system has the type `int32'. */
///* #undef HAVE_INT32 */
//
///* Define to 1 if the system has the type `int8'. */
///* #undef HAVE_INT8 */
//
///* The size of a `int', as computed by sizeof. */
//#define SIZEOF_INT 4
//
///* The size of a `long', as computed by sizeof. */
//#define SIZEOF_LONG 4
//
///* Compatibility stuff. */
//
///* Define as 0 or 1 according to the floating point format suported by the
//   machine */
//#define HAVE_IEEEFP 1
//
///* Set the native cpu bit order (FILLORDER_LSB2MSB or FILLORDER_MSB2LSB) */
//#define HOST_FILLORDER FILLORDER_LSB2MSB
//
///* Native cpu byte order: 1 if big-endian (Motorola) or 0 if little-endian
//   (Intel) */
//#define HOST_BIGENDIAN 1
//
///* Support CCITT Group 3 & 4 algorithms */
//#undef CCITT_SUPPORT
//
///* Support JPEG compression (requires IJG JPEG library) */
//#define JPEG_SUPPORT 1
//
///* Support LogLuv high dynamic range encoding */
//#undef LOGLUV_SUPPORT
//
///* Support LZW algorithm */
//#undef LZW_SUPPORT
//
///* Support NeXT 2-bit RLE algorithm */
//#undef NEXT_SUPPORT
//
///* Support Old JPEG compresson (read contrib/ojpeg/README first! Compilation
//   fails with unpatched IJG JPEG library) */
///* #undef OJPEG_SUPPORT */
//
///* Support Macintosh PackBits algorithm */
//#undef PACKBITS_SUPPORT
//
///* Support Pixar log-format algorithm (requires Zlib) */
//#undef PIXARLOG_SUPPORT
//
///* Support ThunderScan 4-bit RLE algorithm */
//#undef THUNDER_SUPPORT
//
///* Support Deflate compression */
//#undef ZIP_SUPPORT
//
///* Support strip chopping (whether or not to convert single-strip uncompressed
//   images to mutiple strips of ~8Kb to reduce memory usage) */
//#undef STRIPCHOP_DEFAULT //TIFF_STRIPCHOP
//
///* Enable SubIFD tag (330) support */
//#undef SUBIFD_SUPPORT
//
///* Treat extra sample as alpha (default enabled). The RGBA interface will
//   treat a fourth sample with no EXTRASAMPLE_ value as being ASSOCALPHA. Many
//   packages produce RGBA files but don't mark the alpha properly. */
//#undef DEFAULT_EXTRASAMPLE_AS_ALPHA
//
///* Pick up YCbCr subsampling info from the JPEG data stream to support files
//   lacking the tag (default enabled). */
//#undef CHECK_JPEG_YCBCR_SUBSAMPLING
//
///* Support MS MDI magic number files as TIFF */
//#undef MDI_SUPPORT

/*
 * Feature support definitions.
 * XXX: These macros are obsoleted. Don't use them in your apps!
 * Macros stays here for backward compatibility and should be always defined.
 */
 /*
#define COLORIMETRY_SUPPORT
#define YCBCR_SUPPORT
#define CMYK_SUPPORT
#define ICC_SUPPORT
#define PHOTOSHOP_SUPPORT
#define IPTC_SUPPORT
*/
#endif /* _TIFFCONF_ */
